### PR TITLE
go lint

### PR DESCRIPTION
**Pull request by jackyzha0**
- update gitignore
- update deps
- add linter workflow

### CODE REVIEW

**Review by jamesmengo — COMMENTED** [review]
Will this run the linter when pushing?

**Comment by jackyzha0** [comment]
> Will this run the linter when pushing?

This will run the linter on pull requests. Not sure if we can set up a pre-commit hook or something

**Review by jamesmengo — APPROVED** [review]

**Comment by jamesmengo** [comment]
https://www.notion.so/Pre-Commit-Git-Hook-Linter-9e6c600025c24896b0d718de477a663f

**Comment by nandanmen** [comment]
> https://www.notion.so/Pre-Commit-Git-Hook-Linter-9e6c600025c24896b0d718de477a663f

Thanks for doing this!

**Review by nandanmen — APPROVED** [review]

**Pull request merged**
